// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database'; // Corrected import path

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://astlewhbixchznepusca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzdGxld2hiaXhjaHpuZXB1c2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NjI2NzgsImV4cCI6MjA1OTQzODY3OH0.bk2dUAzbY4pZR4Z-Um6Bzvm8UJ6Qzupa_oxlgJBijWI";

// إضافة تحقق للتأكد من وجود بيانات الاتصال
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('بيانات اتصال Supabase غير موجودة. يرجى التأكد من تكوين متغيرات البيئة الصحيحة.');
}

// للتأكد من أن المتغيرات تم تحميلها بشكل صحيح
console.log('Supabase URL:', SUPABASE_URL);
console.log('Supabase key loaded:', SUPABASE_PUBLISHABLE_KEY ? 'Yes' : 'No');

// إعداد عميل Supabase مع إعادة المحاولة وزيادة المهلة الزمنية
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  global: {
    fetch: (...args: Parameters<typeof fetch>) => {
      return fetch(...args).catch(err => {
        console.error('Supabase fetch error:', err);
        throw err;
      });
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// تحسين دالة التحقق من الاتصال
export const checkConnection = async () => {
  try {
    console.log('جاري التحقق من الاتصال بقاعدة البيانات...');
    
    // التحقق من وجود الجداول المطلوبة
    const { data: tables, error: tablesError } = await supabase
      .from('properties')
      .select('count')
      .limit(1);
      
    if (tablesError) {
      if (tablesError.code === 'PGRST116') {
        console.error('جدول العقارات غير موجود');
        throw new Error('جدول العقارات غير موجود في قاعدة البيانات');
      }
      throw tablesError;
    }

    // التحقق من صلاحيات المستخدم
    const { data: session } = await supabase.auth.getSession();
    if (session?.session?.user) {
      const { data: profile, error: profileError } = await supabase
        .from('profiles')
        .select('role')
        .eq('id', session.session.user.id)
        .single();
        
      if (profileError) {
        console.error('خطأ في التحقق من صلاحيات المستخدم:', profileError);
      } else {
        console.log('دور المستخدم:', profile?.role);
      }
    }

    console.log('تم الاتصال بنجاح بقاعدة البيانات');
    return true;
  } catch (error: any) {
    console.error('فشل الاتصال بقاعدة البيانات:', error);
    throw error;
  }
};

// التحقق من الاتصال عند بدء التطبيق
checkConnection().catch(error => {
  console.error('فشل التحقق من الاتصال:', error);
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
